### ISSUE TITLE
add a note that super.initialize should be called when overriding initialize

### ISSUE THREAD

**Issue by benatkin** [amccloud/backbone-tastypie#5]
This initialize() method:

https://github.com/amccloud/backbone-tastypie/blob/master/backbone-tastypie.js#L31

...changes Backbone.Collection so that initialize() actually does something, so it needs to be called by the subclass to get the behavior that it provides.

**Comment by amccloud** [comment]
Yea that really sucks. Ive been trying to find away around that. I think I'm going to move the initialize code into the constructor.

**Comment by benatkin** [comment]
I think requiring initialize() in a subclass to call the parent's initialize() is better design. I wish Backbone did that. You need to do it if you subclass Backbone.Collection twice, and override initialize() in each, anyway.
