### ISSUE TITLE
filters in a Backbone.Collection

### ISSUE THREAD

**Issue by dominicglenn** [amccloud/backbone-tastypie#7]
I've setup two separate collections on a page and setting up the filters for one (passed as an arg to the constructor) causes the filters on the other to be set, because they both reference the original filters variable on the Backbone.Collection.prototype object.

I solved this issue by using the following code locally:

```
_.extend(Backbone.Collection.prototype, {
        initialize: function(collections, options) {
            _.bindAll(this, 'fetchNext', 'fetchPrevious');

            this.meta = {};

            this.filters = {
                limit: Backbone.Tastypie.defaultLimit,
                offset: 0
            };

            if (options && options.filters)
                _.extend(this.filters, options.filters);
        },
```

Basically I changed this.filters to be a variable that is declared inside the constructor and bound to the collection instance; this solved my problem.

**Comment by amccloud** [comment]
Good call. Thanks!
