### ISSUE TITLE
reset() function not resetting limit and offset

### ISSUE THREAD

**Issue by dominicglenn** [amccloud/backbone-tastypie#9]
I believe that calling the reset function on a collection should reset the limit and offset of the current collection; it doesn't do this at the moment.

Easy patch code that I have written myself at the moment:

Inside the IIFE for this plugin:

```
var originalResetFunction = Backbone.Collection.prototype.reset;
```

Inside the extend that gives the Backbone.Collection the extra methods:

```
       reset: function (models, options){
            originalResetFunction.apply(this, arguments);
            this.filters = {
                limit: Backbone.Tastypie.defaultLimit,
                offset: 0
            };
            return this;
        },
```

I despise the cheap hack that I had to use but I'm not sure on what the correct way would be of calling the original Backbone.Collection.prototype.reset function would be; the issue is that because we have extended the prototype itself at compile time when it comes to run-time the prototype reset function is already pointing to the new reset function.

It would be good if this feature could get implemented and also a better solution could be presented; I'm interested in finding out what the correct way of doing this would be.

**Comment by amccloud** [comment]
I don't believe this should be the default behavior. imagine you have a user on page 6 of a collection. If you reset for any reason they will be forced back to page 1. Another option would be to bind to `reset` on the collection.

``` javascript
somecollection.on('reset', function(collection) {
    collection.filters = {
        limit: 0,
        offset: 0
    }
});
```
